// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartB.Models;

#nullable disable

namespace PartB.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20240920035340_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartB.Models.Genre", b =>
                {
                    b.Property<long>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1L,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 2L,
                            GenreName = "Comedy"
                        },
                        new
                        {
                            GenreId = 3L,
                            GenreName = "Drama"
                        },
                        new
                        {
                            GenreId = 4L,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 5L,
                            GenreName = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 6L,
                            GenreName = "Romance"
                        });
                });

            modelBuilder.Entity("PartB.Models.Movie", b =>
                {
                    b.Property<long>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovieId"));

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1L,
                            Rating = 88.5m,
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 2L,
                            Rating = 89.7m,
                            Title = "Titanic"
                        },
                        new
                        {
                            MovieId = 3L,
                            Rating = 88.5m,
                            Title = "Inception 2"
                        },
                        new
                        {
                            MovieId = 4L,
                            Rating = 89.7m,
                            Title = "Titanic 2"
                        },
                        new
                        {
                            MovieId = 5L,
                            Rating = 88.5m,
                            Title = "Inception 3"
                        },
                        new
                        {
                            MovieId = 6L,
                            Rating = 89.7m,
                            Title = "Titanic 3"
                        },
                        new
                        {
                            MovieId = 7L,
                            Rating = 88.5m,
                            Title = "Inception 4"
                        },
                        new
                        {
                            MovieId = 8L,
                            Rating = 89.7m,
                            Title = "Titanic 4"
                        },
                        new
                        {
                            MovieId = 9L,
                            Rating = 88.5m,
                            Title = "Inception 5"
                        },
                        new
                        {
                            MovieId = 10L,
                            Rating = 89.7m,
                            Title = "Titanic 5 "
                        },
                        new
                        {
                            MovieId = 11L,
                            Rating = 88.5m,
                            Title = "Inception 6"
                        },
                        new
                        {
                            MovieId = 12L,
                            Rating = 89.7m,
                            Title = "Titanic 6"
                        });
                });

            modelBuilder.Entity("PartB.Models.MovieGenre", b =>
                {
                    b.Property<long>("MovieGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovieGenreId"));

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.HasKey("MovieGenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieGenreId = 1L,
                            GenreId = 1L,
                            MovieId = 1L
                        },
                        new
                        {
                            MovieGenreId = 2L,
                            GenreId = 5L,
                            MovieId = 1L
                        },
                        new
                        {
                            MovieGenreId = 3L,
                            GenreId = 1L,
                            MovieId = 3L
                        },
                        new
                        {
                            MovieGenreId = 4L,
                            GenreId = 5L,
                            MovieId = 3L
                        },
                        new
                        {
                            MovieGenreId = 5L,
                            GenreId = 1L,
                            MovieId = 5L
                        },
                        new
                        {
                            MovieGenreId = 6L,
                            GenreId = 5L,
                            MovieId = 5L
                        },
                        new
                        {
                            MovieGenreId = 7L,
                            GenreId = 1L,
                            MovieId = 7L
                        },
                        new
                        {
                            MovieGenreId = 8L,
                            GenreId = 5L,
                            MovieId = 7L
                        },
                        new
                        {
                            MovieGenreId = 9L,
                            GenreId = 1L,
                            MovieId = 9L
                        },
                        new
                        {
                            MovieGenreId = 10L,
                            GenreId = 5L,
                            MovieId = 9L
                        },
                        new
                        {
                            MovieGenreId = 11L,
                            GenreId = 1L,
                            MovieId = 11L
                        },
                        new
                        {
                            MovieGenreId = 12L,
                            GenreId = 5L,
                            MovieId = 11L
                        },
                        new
                        {
                            MovieGenreId = 13L,
                            GenreId = 3L,
                            MovieId = 2L
                        },
                        new
                        {
                            MovieGenreId = 14L,
                            GenreId = 6L,
                            MovieId = 2L
                        },
                        new
                        {
                            MovieGenreId = 15L,
                            GenreId = 3L,
                            MovieId = 4L
                        },
                        new
                        {
                            MovieGenreId = 16L,
                            GenreId = 6L,
                            MovieId = 4L
                        },
                        new
                        {
                            MovieGenreId = 17L,
                            GenreId = 3L,
                            MovieId = 6L
                        },
                        new
                        {
                            MovieGenreId = 18L,
                            GenreId = 6L,
                            MovieId = 6L
                        },
                        new
                        {
                            MovieGenreId = 19L,
                            GenreId = 3L,
                            MovieId = 8L
                        },
                        new
                        {
                            MovieGenreId = 20L,
                            GenreId = 6L,
                            MovieId = 8L
                        },
                        new
                        {
                            MovieGenreId = 21L,
                            GenreId = 3L,
                            MovieId = 10L
                        },
                        new
                        {
                            MovieGenreId = 22L,
                            GenreId = 6L,
                            MovieId = 10L
                        },
                        new
                        {
                            MovieGenreId = 23L,
                            GenreId = 3L,
                            MovieId = 12L
                        },
                        new
                        {
                            MovieGenreId = 24L,
                            GenreId = 6L,
                            MovieId = 12L
                        });
                });

            modelBuilder.Entity("PartB.Models.MovieGenre", b =>
                {
                    b.HasOne("PartB.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartB.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("PartB.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("PartB.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
